language: cpp

os:
  - osx

before_install:
  - brew install qt5 cln
  - brew link --force qt5
script:
 - ./build-mac.sh

deploy:
  provider: releases
  api_key: $TOKEN
  file: Differ.zip
  skip_cleanup: true
  on:
    tags: true
